### PR TITLE
Add option for offset to account for fixed nav/header

### LINKED ISSUE #5: Suggestion: Add option for offset to account for fixed nav/header
To avoid a fixed nav/header overlapping the content when scrolling down having the option to set an offset height either in config, or as an argument to the smoothScroll function would be useful.

### PR DESCRIPTION
**Pull request by jHards**
Fixes #5

### CODE REVIEW

**Review by babono — APPROVED** [review]

**Comment by jHards** [comment]
@freddydumont is this good to go?

**Comment by freddydumont** [comment]
Sorry I had forgotten about this. Do you wanna add a section in the readme to document the changes? Could be under Examples of usage

**Comment by jHards** [comment]
Fixed an error in `index.js` and provided some additional content to `README.md`

**Comment by jHards** [comment]
@freddydumont, are we good to go?

**Comment by freddydumont** [comment]
See #5

**Pull request closed without merging**
